#  ┌─────────────────────────────┐
#  │  Cross Server Sync Setting  │
#  └─────────────────────────────┘
sync:
  #Port that you set in the config of the Bungeecord. [OPTIONS: 'anyInteger', PLACEHOLDERS: none, DEFAULT: '20154']
  syncPort: 20154
  #Passsword that you set in the config of the Bungeecord. [OPTIONS: 'anyString'', PLACEHOLDERS: none, DEFAULT: 'randomPassword']
  syncPassword: "randomPassword"
  #Heartbeat of the socket connection, don't change this value if you don't know what you are doing! [OPTIONS: 'anyInteger', PLACEHOLDERS: none, DEFAULT: '1000']
  heartbeat: 1000