name: ClientDetector
version: 2.0-BETA
author: Sportkanone123
main: de.sportkanone123.clientdetector.spigot.ClientDetector
load: POSTWORLD
api-version: 1.13

softdepend: [PlaceholderAPI]

commands:
  clientdetector:
    aliases: cd